name: Feed
version: 2.0.0
description: Feed plugin for Flextype
author:
  name: Sergey Romanenko
  email: awilum@msm.com
  url: https://awilum.github.io
homepage: https://github.com/flextype-plugins/feed
documentation: https://github.com/flextype-plugins/feed
changelog: https://github.com/flextype-plugins/feed/blob/master/CHANGELOG.md
bugs: https://github.com/flextype-plugins/feed/issues
icon:
  name: rss
  set: "bootstrap"
license: MIT

dependencies:
  flextype: "^1.0.0-alpha.1"
  twig: "^3.0.0"
